name: Deploy via FTP

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v4
    
    - name: Sync Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Memastikan ke folder yang tepat untuk domain ayakajosseicenter.com
        server-dir: public_html/ayaka_men/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/tests/**
          .env
